version: 2
updates:
  - package-ecosystem: maven
    directories:
      - "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
    ignore:
    - dependency-name:  com.sap.cds:*
      versions:
      - ">=4"

  - package-ecosystem: npm
    directories:
      - "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
