---
management:
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults:
      enabled: false
    ping:
      enabled: true
    db:
      enabled: true
logging:
  level:
    '[com.sap.cds.services.impl.runtime.CdsRuntimeImpl]': DEBUG
    '[com.sap.cloud.sdk.datamodel.odata]': DEBUG
    '[com.sap.cds.services.impl.odata]': DEBUG
---
spring:
  config.activate.on-profile: default
  sql.init.platform: h2
cds:
  security:
    mock:
      users:
        - name: test.user@example.com
          password: myPass
          roles:
            - cds.Developer
---
spring:
  config.activate.on-profile: test
cds:
  security:
    mock:
      users:
        - name: test.user@example.com
          password: myPass
          roles:
            - cds.Developer
  data-source.auto-config.enabled: false
  index-page.enabled: true
  #remote:
    #services:
      #NotificationProviderService:
        #destination.name: SAP_Notifications
        #type: odata-v2
        #http:
          #suffix: /v2
          #service: Notification.svc
          #csrf.enabled: true
  environment:
    production:
      enabled: true

