/*
 * © 2026 SAP SE or an SAP affiliate company and cds-feature-notifications contributors.
 */
package com.sap.cds.notifications.helpers;

import com.sap.cds.adapter.edmx.EdmxI18nProvider;
import com.sap.cds.reflect.CdsEvent;
import com.sap.cds.services.runtime.CdsRuntime;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Shared helper for i18n resolution, locale discovery, and HTML template loading. Used by both
 * NotificationTypeBuilder and NotificationTemplateBuilder to avoid code duplication.
 */
public class I18nHelper {

  private static final Logger logger = LoggerFactory.getLogger(I18nHelper.class);
  private static final String I18N_PREFIX = "{i18n>";

  private final CdsRuntime runtime;
  private EdmxI18nProvider i18nProvider;
  private final Map<String, String> htmlCache = new HashMap<>();

  public I18nHelper(CdsRuntime runtime) {
    this.runtime = runtime;
  }

  private EdmxI18nProvider getProvider() {
    if (i18nProvider == null) {
      i18nProvider = runtime.getProvider(EdmxI18nProvider.class);
    }
    return i18nProvider;
  }

  /**
   * Discover available locales from the EdmxI18nProvider. This dynamically detects which languages
   * have i18n translations defined in the application's _i18n/ properties files, rather than
   * relying on a hardcoded list. Always includes English as a fallback.
   *
   * @since cds-services 4.9.0
   */
  public Set<Locale> getAvailableLocales() {
    EdmxI18nProvider provider = getProvider();
    if (provider != null) {
      Set<Locale> locales = provider.getLocales();
      if (!locales.isEmpty()) {
        return locales;
      }
    }
    logger.warn("EdmxI18nProvider.getLocales() returned no locales, falling back to English only");
    return Set.of(Locale.ENGLISH);
  }

  /**
   * Get locales that have actual notification translations for the given event. Compares each
   * locale's resolved {@code notification.template.title} against the English value. A locale is
   * included only if its title differs from English AND is fully resolved (no unresolved {@code
   * {i18n>KEY}} placeholders remain). English is always included.
   *
   * <p>This filters out locales that only exist because of {@code @sap/cds/common} framework
   * translations (e.g. "Created By" in 37 languages) but have no app-specific notification texts.
   *
   * <p>Note: {@link #resolveI18n(String, java.util.Map)} returns {@code null} when any placeholder
   * cannot be resolved. Such locales are excluded to prevent raw placeholder strings from reaching
   * ANS.
   */
  public Set<Locale> getAvailableLocalesForEvent(CdsEvent event) {
    Set<Locale> allLocales = getAvailableLocales();
    Map<String, String> enTexts = getI18nTexts(Locale.ENGLISH);
    String enTitle = resolveAnnotationValue(event, "notification.template.title", enTexts);

    Set<Locale> filtered = new LinkedHashSet<>();
    for (Locale locale : allLocales) {
      // Locale.ROOT produces "und" (undefined) in BCP-47, which represents the default
      // i18n.properties file. Map it to English since the content is the same and "und"
      // is not a valid ANS language code.
      if (locale.getLanguage().isEmpty()) {
        filtered.add(Locale.ENGLISH);
        continue;
      }
      if ("en".equals(locale.getLanguage())) {
        filtered.add(locale);
        continue;
      }
      Map<String, String> localeTexts = getI18nTexts(locale);
      String localeTitle =
          resolveAnnotationValue(event, "notification.template.title", localeTexts);
      if (localeTitle != null && !Objects.equals(enTitle, localeTitle)) {
        filtered.add(locale);
      }
    }

    logger.debug(
        "Filtered locales for '{}': {} (skipped {} without notification translations)",
        event.getName(),
        filtered,
        allLocales.size() - filtered.size());
    return filtered;
  }

  /**
   * Get i18n texts for a given locale from the EdmxI18nProvider. The provider reads from
   * edmx/_i18n/i18n.json which is generated by the CDS compiler from _i18n/i18n*.properties files
   * located next to the .cds source files.
   */
  public Map<String, String> getI18nTexts(Locale locale) {
    EdmxI18nProvider provider = getProvider();
    if (provider != null) {
      return provider.getTexts(locale);
    }
    logger.warn("EdmxI18nProvider not available, i18n resolution will not work");
    return Collections.emptyMap();
  }

  /** Extract i18n key from annotation value like {i18n>KEY} and resolve using EdmxI18nProvider. */
  public String resolveAnnotationValue(
      CdsEvent event, String annotationPath, Map<String, String> i18nTexts) {
    String annotationValue =
        event.findAnnotation(annotationPath).map(a -> (String) a.getValue()).orElse(null);

    if (annotationValue == null) {
      return null;
    }

    return resolveI18n(annotationValue, i18nTexts);
  }

  /**
   * Resolve all {i18n>KEY} patterns in a string using the i18n texts map. Supports both
   * single-placeholder values (e.g. "{i18n>TITLE}") and multi-placeholder values (e.g.
   * "{i18n>GREETING}, {i18n>BODY}").
   *
   * @return the resolved string, or {@code null} if any placeholder could not be resolved (i.e. the
   *     key was not present in {@code i18nTexts})
   */
  public String resolveI18n(String value, Map<String, String> i18nTexts) {
    if (value == null || !value.contains(I18N_PREFIX)) {
      return value;
    }

    for (Map.Entry<String, String> entry : i18nTexts.entrySet()) {
      value = value.replace(I18N_PREFIX + entry.getKey() + "}", entry.getValue());
    }
    return value.contains(I18N_PREFIX) ? null : value;
  }

  /**
   * Load HTML content from classpath resource and resolve {i18n>KEY} placeholders. HTML content is
   * cached after first load since only i18n values change per language.
   */
  public String loadHtmlFromClasspath(String filePath, Map<String, String> i18nTexts) {
    String content =
        htmlCache.computeIfAbsent(
            filePath,
            path -> {
              try (InputStream is = getClass().getClassLoader().getResourceAsStream(path)) {
                if (is != null) {
                  return new String(is.readAllBytes(), StandardCharsets.UTF_8);
                } else {
                  logger.error("HTML file not found: {}", path);
                  return null;
                }
              } catch (Exception e) {
                logger.error("Failed to load HTML file: {}", path, e);
                return null;
              }
            });

    if (content == null) {
      return null;
    }

    // Resolve {i18n>KEY} placeholders in the HTML content
    String resolvedHtml = resolveI18n(content, i18nTexts);
    if (resolvedHtml == null) {
      logger.error("Unresolved i18n placeholder(s) in HTML template: {}", filePath);
      return null;
    }

    // Minify HTML: remove comments and unnecessary whitespace
    String compactHtml =
        resolvedHtml
            .replaceAll("(?s)<!--.*?-->", "")
            .replaceAll(">\\s+<", "><")
            .replaceAll("\\s{2,}", " ")
            .trim();

    logger.debug(
        "Loaded HTML file: {} (original: {} bytes, resolved+compacted: {} bytes)",
        filePath,
        content.length(),
        compactHtml.length());
    return compactHtml;
  }
}
