name: Label issues

permissions: {}

on:
  issues:
    types:
      - opened

jobs:
  label-issue:
    uses: cap-java/.github/.github/workflows/issue.yml@1040e19f5ca25c2942f2fa56632f430e9a2549be #main
