name: Label issues

permissions: {}

on:
  issues:
    types:
      - opened

jobs:
  label-issue:
    uses: cap-java/.github/.github/workflows/issue.yml@b0271722321563f7d0593a0004dce2880349ee4e #main
