name: Deploy to Maven Central

on:
  release:
    types: [ "released" ]

jobs:
  release:
    uses: cap-java/.github/.github/workflows/release.yml@1040e19f5ca25c2942f2fa56632f430e9a2549be #main
    with:
      blackduck-project-name: com.sap.cds.feature.notifications
      blackduck-included-modules: cds-feature-notifications
    secrets: inherit
