name: Deploy to Maven Central

on:
  release:
    types: [ "released" ]

jobs:
  release:
    uses: cap-java/.github/.github/workflows/release.yml@b0271722321563f7d0593a0004dce2880349ee4e #main
    with:
      blackduck-project-name: com.sap.cds.feature.notifications
      blackduck-included-modules: cds-feature-notifications
    secrets: inherit
